// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "'hQYQPOOObQPO'#C`OmQPO'#C_OrQPO'#CdOzQPO'#ChOOQO'#Cp'#CpOOQO'#Ci'#CiQYQPOOO!PQPO,58yOzQPO,59OO![QPO,59QOOQO'#Ce'#CeOOQO,59S,59SOOQO-E6g-E6gOOQO'#C`'#C`O!aQQO1G.eO!PQPO'#CcOOQO'#Cs'#CsOOQO'#Cj'#CjO!rQPO1G.jOOQO'#Cg'#CgO!zQPO1G.lO![QPO1G.lO!PQPO,58|O!PQPO,58|OOQO7+$P7+$PO#]QQO,58}OOQO-E6h-E6hOOQO7+$U7+$UO#nQQO'#ClO$]QPO7+$WO$nQPO7+$WOOQO7+$W7+$WO$vQPO7+$WOOQO-E6i-E6iOOQO1G.h1G.hO%XQQO1G.hOOQO1G.i1G.iOOQO-E6j-E6jO%|QPO<<GrOOQO<<Gr<<GrO&UQPO<<GrO&gQPO<<GrP&oQPO'#CkOOQOAN=^AN=^O&}QPOAN=^P'VQPO,59VPOQO,59V,59VOOQOG22xG22xPOQO1G.q1G.q",
  stateData: "'h~OcOSPOS~OePOsSO~OfSXoXXpXX~OfWO~OoXOpYO~OeZO~OTaOe^Ol`O~OedO~OhgOigOjhOkhOniO~OeZOnlO~OTaOe^Ol`OqoOrpO~OhgOigOjhOkhOmuO~OhgOigOjhOkhOT`Xe`Xl`Xq`Xr`X~OTaOe^Ol`OqwOrxO~OrxOe_a~OTaOe^Ol`OqzOrxO~OhgOigOjUikUinUimUiTUieUilUiqUirUi~Or|Oe_i~OTaOe^Ol`Oq}Or|O~Or|Oe_a~OTaOe^Ol`Oq!PO~Or!QOe_i~OTaOe^Ol`Oq!RO~Okk~",
  goto: "#jhPPPimPqqi}i!Yi!`!f!l!rPPP#QPP#UTTOVSQOVeaW`eghnqy{!OSROVQ[STbXcQeYRqfQVOR]VQcXRkcQfYRrfQneUvny!OQyqR!O{TUOVQ_WQj`[menqy{!OQsgRth",
  nodeNames: "⚠ LineComment Program Constant Variable Number Operation Parenthesized Replacement Symbol Command CommandName Start",
  maxTerm: 35,
  skippedNodes: [0,1],
  repeatNodeCount: 4,
  tokenData: "%y~ReXY!dYZ!d]^!dpq!dxy!uyz!zz{#P{|#U|}#Z}!O#`!O!P#n!P!Q$^!Q![#|!]!^$}!_!`%S!c!}%X#Q#R%j#R#S%X#T#o%X#o#p%o#q#r%t~!iSc~XY!dYZ!d]^!dpq!d~!zOl~~#POm~~#UOh~~#ZOj~~#`Oq~~#eRkQ!O!P#n!Q![#|!`!a$X~#qP!Q![#t~#yPT~!Q![#t~$RQT~!O!P#t!Q![#|P$^OoP~$cPi~!P!Q$f~$kSP~OY$fZ;'S$f;'S;=`$w<%lO$f~$zP;=`<%l$f~%SOn~~%XOf~~%^Se~!Q![%X!c!}%X#R#S%X#T#o%X~%oOs~~%tOp~~%yOr~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  tokenPrec: 297
})
