// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Variable = 4,
  Expression = 5,
  Operation = 6,
  Operand = 10,
  Number = 11,
  LSymbol = 13,
  Symbol = 14,
  Instruction = 16,
  CommandName = 17,
  InstructionArg = 18
