// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "'nQYQPOOObQPO'#C`OmQPO'#C_OrQPO'#ChOwQPO'#CkO|QPO'#CoOOQO'#Cw'#CwOOQO'#Cp'#CpQYQPOOO!RQPO,58yO|QPO,59SO!^QPO,59VOOQO'#Cj'#CjOOQO'#Cq'#CqO!cQPO,59ZOOQO-E6n-E6nOOQO'#C`'#C`O!kQQO1G.eO!RQPO'#CeOOQO'#Ca'#CaO!|QPO1G.nOOQO'#Cm'#CmO#UQPO'#ClO#gQPO1G.qO!^QPO1G.qOOQO-E6o-E6oOOQO1G.u1G.uOOQO'#Cc'#CcOOQO'#Cd'#CdO!RQPO,58|O!RQPO,58|OOQO7+$P7+$PO#oQQO'#CfO$QQPO,59POOQO7+$Y7+$YO$VQQO'#CnOOQO'#Cs'#CsO$tQPO,59WO%VQPO7+$]OOQO7+$]7+$]O%_QPO7+$]OOQO-E6p-E6pOOQO1G.h1G.hO%gQQO1G.hOOQO1G.k1G.kOOQO-E6q-E6qOOQO<<Gw<<GwO&XQPO<<GwP&aQPO'#CrOOQOAN=cAN=cPOQO,59^,59^",
  stateData: "&i~OjOSPOS~OlPOxTO~OmSXu]Xv^X~OmXO~OuYO~OvZO~Ol[O~OZcOl`OrbO~OleO~Ol[OtjO~OnkOokOplOqlOtoO~Ol[OtrO~OZcOl`OrbOt`Xw`X~OtwOwvO~OnkOokOplOqlOsYX~Os|O~OnkOokOplOqlOZbXlbXrbXtbXwbX~OZcOl`OrbOt`aw`a~Ot!OOlfa~Ot!OOw!PO~OnkOokOpUiqUitUisUiZUilUirUiwUi~Ot!ROlfa~Ow!SO~Oqq~",
  goto: "#{lPPPmq}u!_!eu!jPm!m!qm!{#R#Vm#Z#a#k#qPPP#wTUOWSQOW]cXbfmnuQaXQpbSsfuQzmR{nXmaps{VnapsRqbTROWSSOWX]TY^dQgZRxhTfZhTtfuQWOR_WQ^TQdYTi^dQhZRyhQufR}uTVOW",
  nodeNames: "⚠ LineComment Program Constant Variable Expression Operation Op Op Parenthesized Operand Number Replacement LSymbol Symbol Command Instruction CommandName InstructionArg Start",
  maxTerm: 40,
  skippedNodes: [0,1],
  repeatNodeCount: 4,
  tokenData: "%q~RdXY!aYZ!a]^!apq!axy!ryz!wz{!|{|#R|}#W}!O#]!O!P#k!P!Q$Z!Q![#y![!]$z!]!^%P!_!`%U!c!}%Z#Q#R%l#R#S%Z#T#o%Z~!fSj~XY!aYZ!a]^!apq!a~!wOr~~!|Os~~#ROn~~#WOp~~#]Ow~~#bRqQ!O!P#k!Q![#y!`!a$U~#nP!Q![#q~#vPZ~!Q![#q~$OQZ~!O!P#q!Q![#yP$ZOuP~$`Po~!P!Q$c~$hSP~OY$cZ;'S$c;'S;=`$t<%lO$c~$wP;=`<%l$c~%POv~~%UOt~~%ZOm~~%`Sl~!Q![%Z!c!}%Z#R#S%Z#T#o%Z~%qOx~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  tokenPrec: 252
})
